In [1]:
import numpy as np

In [2]:
list_ = ['1','2','3','4','5']

In [3]:
array_list = np.array(object = list_)

Q.1) Yes Both of them have different data types.

In [18]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'list'>
Data type of array_list: <U1


In [19]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_:")
for item in list_:
    print(type(item))

print("Data type of elements in array_list:")
for item in array_list:
    print(item.dtype)


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<U1
<U1
<U1
<U1
<U1


Yes, there will be a difference in the data type of the elements in array_list after specifying dtype=int. It will convert the elements to integer data type. To print the data types of elements in both variables after this change:

In [20]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for item in list_:
    print(type(item))

print("Data type of elements in array_list:")
for item in array_list:
    print(item.dtype)


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
int64
int64
int64
int64
int64


In [21]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# (i) Shape of the array
shape = num_array.shape

# (ii) Size of the array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [22]:
import numpy as np

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
