### 1. Data Structures in TensorFlow

TensorFlow uses several key data structures to handle data:

- **Tensors**: The primary data structure in TensorFlow, representing multi-dimensional arrays. Tensors are immutable and have a fixed size.
  - **Example**: `tf.constant([1, 2, 3])`

- **Variables**: Used to store mutable data that can change during training. Variables are commonly used for weights and biases in neural networks.
  - **Example**: `tf.Variable([1, 2, 3], dtype=tf.float32)`

- **Data Pipelines**: TensorFlow provides the `tf.data` API to build efficient data input pipelines.
  - **Example**: `tf.data.Dataset.from_tensor_slices([1, 2, 3])`

- **Sparse Tensors**: Efficiently represent tensors with a lot of zero entries.
  - **Example**: `tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])`

### 2. TensorFlow Constant vs. TensorFlow Variable

**TensorFlow Constant**: Immutable data structure, values cannot be changed once assigned.
- **Example**:
  ```python
  tf_constant = tf.constant([1, 2, 3])
  ```

**TensorFlow Variable**: Mutable data structure, values can be changed during training.
- **Example**:
  ```python
  tf_variable = tf.Variable([1, 2, 3], dtype=tf.float32)
  tf_variable.assign([4, 5, 6])  # Changing the values
  ```

### 3. Matrix Operations in TensorFlow

**Matrix Addition**:
- **Example**:
  ```python
  A = tf.constant([[1, 2], [3, 4]])
  B = tf.constant([[5, 6], [7, 8]])
  C = tf.add(A, B)
  ```

**Matrix Multiplication**:
- **Example**:
  ```python
  A = tf.constant([[1, 2], [3, 4]])
  B = tf.constant([[5, 6], [7, 8]])
  C = tf.matmul(A, B)
  ```

**Element-wise Operations**:
- **Example**:
  ```python
  A = tf.constant([[1, 2], [3, 4]])
  B = tf.constant([[5, 6], [7, 8]])
  C = tf.multiply(A, B)  # Element-wise multiplication
  ```


In [3]:

### Creating and Manipulating Matrices

import tensorflow as tf

# 1. Create a normal matrix A with dimensions 2x2
A = tf.random.normal([2, 2])
print("Matrix A:\n", A.numpy())

# 2. Create a Gaussian matrix B with dimensions 2x2
B = tf.random.truncated_normal([2, 2])
print("Matrix B:\n", B.numpy())

# 3. Create a matrix C with dimensions 2x2, with a mean of 2 and a stddev of 0.5
C = tf.random.normal([2, 2], mean=2, stddev=0.5)
print("Matrix C:\n", C.numpy())

# 4. Perform matrix addition between A and B
D = tf.add(A, B)
print("Matrix D (A + B):\n", D.numpy())

# 5. Perform matrix multiplication between C and D
E = tf.matmul(C, D)
print("Matrix E (C * D):\n", E.numpy())


### Performing Additional Matrix Operations
# 1. Create a matrix F with dimensions 2x2, initialized with random values
F = tf.random.uniform([2, 2])
print("Matrix F:\n", F.numpy())

# 2. Calculate the transpose of matrix F
G = tf.transpose(F)
print("Matrix G (Transpose of F):\n", G.numpy())

# 3. Calculate the element-wise exponential of matrix F
H = tf.exp(F)
print("Matrix H (Element-wise exponential of F):\n", H.numpy())

# 4. Create a matrix I by concatenating F and G horizontally
I = tf.concat([F, G], axis=1)
print("Matrix I (F and G concatenated horizontally):\n", I.numpy())

# 5. Create a matrix J by concatenating F and H vertically
J = tf.concat([F, H], axis=0)
print("Matrix J (F and H concatenated vertically):\n", J.numpy())


Matrix A:
 [[ 0.02536518 -0.01473116]
 [-0.11626393 -0.40190542]]
Matrix B:
 [[ 0.96161324  1.2214813 ]
 [-0.8207882  -1.5228657 ]]
Matrix C:
 [[2.8366163 2.5898757]
 [1.91201   2.4813943]]
Matrix D (A + B):
 [[ 0.9869784   1.2067502 ]
 [-0.93705213 -1.9247711 ]]
Matrix E (C * D):
 [[ 0.3728304 -1.5618305]
 [-0.4380833 -2.4687977]]
Matrix F:
 [[0.40704417 0.36494696]
 [0.10853517 0.4726498 ]]
Matrix G (Transpose of F):
 [[0.40704417 0.10853517]
 [0.36494696 0.4726498 ]]
Matrix H (Element-wise exponential of F):
 [[1.5023705 1.4404376]
 [1.1146442 1.6042395]]
Matrix I (F and G concatenated horizontally):
 [[0.40704417 0.36494696 0.40704417 0.10853517]
 [0.10853517 0.4726498  0.36494696 0.4726498 ]]
Matrix J (F and H concatenated vertically):
 [[0.40704417 0.36494696]
 [0.10853517 0.4726498 ]
 [1.5023705  1.4404376 ]
 [1.1146442  1.6042395 ]]
